### PR TITLE
Add support pylint for 3.0

### PR DESCRIPTION
**Pull request by tl24**
This PR adds support for pylint 3.0 by not using removed interface support

### CODE REVIEW

**Review by gitesh-sigmoid — APPROVED** [review]
LGTM!

Tested this changes on my local.

**Comment by 0xfabioo** [comment]
@rasjani Can you please have a look at this?

**Review by maduka-ariyasiri — APPROVED** [review]
I've tested changes locally with Pylint version 2.17.7 and 3.0.1.

**Review by rasjani — APPROVED** [review]
Looks ok -  I'll verify things work later this week and prepare a release if things still work as expected

**Comment by 0xfabioo** [comment]
@rasjani When can we expect a release? We can't currently update to pylint 3.0 because of this issue.

**Comment by qi55wyqu** [comment]
This is also keeping us from upgrading to pylint 3. A new release with this fix would be very much appreciated.

**Comment by rasjani** [comment]
https://pypi.org/project/pylint-junit/0.3.3/ -- out now

**Pull request merged**
